// Generated by Wrangler on Wed Aug 14 2024 19:11:52 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  TOKENS: KVNamespace;
  CARDANO_V1_MAINNET: KVNamespace;
  CARDANO_V1_PREPROD: KVNamespace;
  CARDANO_V1_PREVIEW: KVNamespace;
}
