// Generated by Wrangler on Tue Aug 13 2024 21:16:31 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  TOKENS: KVNamespace;
}
