#:schema node_modules/wrangler/config-schema.json
name = "cardano"
main = "src/index.ts"
compatibility_date = "2024-08-06"
routes = [{ pattern = "cardano.utxoedge.com", custom_domain = true }]

[[kv_namespaces]]
id = "c1e7a9c9c30e495c9c4dd3188c47f842"
binding = "TOKENS"

[[env.production.kv_namespaces]]
id = "c1e7a9c9c30e495c9c4dd3188c47f842"
binding = "TOKENS"
